name: Movies CI/CD

run-name: ${{ github.actor }} is testing out Github Actions!

env:
  # The name of the main module repository
  main_project_module: app

  # The name used in artifact names
  playstore_name: MoviesApp

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  Movies-Actions:
    runs-on: ubuntu-latest
    env:
      # Keystore, Fastlane'ın injected signing properties için gerekli ENV'ler
      RELEASE_STORE_FILE: keystore.jks
      RELEASE_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      RELEASE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      ANDROID_KEYSTORE_PATH: ./keystore.jks

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Decode keystore from secrets
      - name: Decode keystore from secrets
        run: |
          if [ -z "${{ secrets.KEYSTORE_BASE64 }}" ]; then
            echo "Missing KEYSTORE_BASE64 secret"; exit 1;
          fi
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > "$ANDROID_KEYSTORE_PATH"
          ls -l "$ANDROID_KEYSTORE_PATH"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install gems
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Lint (Fastlane)
        run: bundle exec fastlane checks

      - name: Run Unit Tests (Fastlane)
        run: bundle exec fastlane tests

      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Results
          path: ${{ env.main_project_module }}/build/test-results/testDebugUnitTest/

      - name: Upload Unit Test Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test HTML Report
          path: ${{ env.main_project_module }}/build/reports/tests/testDebugUnitTest/

      - name: Build signed APK (Fastlane)
        run: bundle exec fastlane apk_release

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.playstore_name }} - APK(s) release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/release/